FORMAT: 1A

# TOCAT

TOCAT is management operational tool that coordinates enterprise value chain from sales to final products

# Group Order API


## Orders Collection [/orders/?paid={paid_status}&sorted_by={sorted_by}&search_query={query}]
### List all Orders [GET]


+ Parameters

    + paid (boolean) - Filtering on paid orders

    + sorted_by (string) - Sorting on orders
    
        + Values
        
            + `invoiced_budget`
            + `created_at`
            + `free_budget`
            + `allocatable_budget`
            + `name`

    + search_query (string) - Search on orders using name or description as a key



+ Response 200 (application/json)

        [{
          "id": 1,  
          "name" : "SuperClient - Project X phase1",
          "invoiced_budget": 400.00, 
          "allocatable_budget": 400.00, 
          "free_budget" : 400.00, 
          "links" : [{
            "href" : "/order/1",
            "rel"  : "self"
          }]
        }, 
         {
          "id": 2,  
          "name" : "SuperClient - Project X phase1 templating", 
          "invoiced_budget": 400.00, 
          "allocatable_budget": 400.00, 
          "free_budget" : 400.00, 
          "links" : [{
            "href" : "/order/2",
            "rel"  : "self"
          }]
        }]

### Create an Order [POST]
+ Request (application/json)

        {
          "invoiced_budget": 150.00, 
          "allocatable_budget": 60.00, 
          "name" : "SuperClient - Project X phase1", 
          "description" : "This is just a test order for SuperClient",
          "team":  {
            "id" : 1
          }
        }

+ Response 201 (application/json)

        {
            "id": 2,
            "links": {
                "href": "/order/2",
                "rel": "self"
            }
        }



## Order [/order/{id}]
A single Order object with all its details

+ Parameters
    + id (required, number, `2`) ... Numeric `id` of the Order to perform action with. 

### Retrieve an Order [GET]

+ Response 200 (application/json)

        {
          "id": 2, 
          "invoiced_budget": 50.00, 
          "allocatable_budget": 50.00, 
          "free_budget" : 50.00, 
          "name" : "SuperClient - Project X phase1 templating", 
          "description" : "This is a SubOrder for templating work done in Team2",
          "paid" : false,
          "completed" : false,
          "parent_order" : {
            "id"   : 1,
            "href" : "/order/1"
          },
          "invoice" : {
            "id"   : 2,
            "href" : "/invoice/2"
          },
          "team":  {
            "id"   : 2,
            "name" : "Team2",
            "href" : "/team/2"
          },
          "links" : [{
            "href" : "/order/2",
            "rel"  : "self"
          },
          {
            "href" : "/order/2/paid",
            "rel"  : "setpaid"
          },
          {
            "href" : "/order/2/invoice",
            "rel"  : "invoice"
          },
          {
            "href" : "/order/2/suborder",
            "rel"  : "suborder"
          }],
          "tasks": [
            {
              "id": 5,
              "external_id": "TST-102",
              "links": [
                {
                  "href": "/tasks/5",
                  "rel": "self"
                },
                {
                  "href": null,
                  "rel": "external"
                }
              ]
            }],
          "sub_orders": [
            {
              "id": 7,
              "name": "super order",
              "invoiced_budget": "50.0",
              "allocatable_budget": "50.0",
              "free_budget": "50.0",
              "links": {
                "url": "/orders/7",
                "rel": "self"
              }
            }
          ]
        }


### Remove an Order [DELETE]
+ Response 200

### Edit an Order [PATCH]
To update an Order send a JSON with updated value for one or more of the Order resource attributes. All attributes values (states) from the previous version of this Order are carried over by default if not included in the hash. Using this action you can update only the following attributes: invoiced_budget, allocatable_budget, name, description, team

+ Request (application/json)

        {
          "invoiced_budget": 500.00, 
          "allocatable_budget": 500.00, 
          "name" : "SuperClient - Project X phase1 templating", 
          "description" : "This is a SubOrder for templating work done in Team2",
          "team":  {
            "id" : 2,
            "href" : "/team/2"
          }
        }

+ Response 200


## Invoice relation [/order/{id}/invoice] 
Updates an order with Invoice information. You can not change invoice when order is set as paid or completed.

### Add Invoice to Order [POST]

+ Request (application/json)

        { "id" : 1 }


+ Response 200

## Complete order [/order/{id}/complete] 
Set order as completed, closing it for further changes and creating transaction in team payment account

### Complete order [POST]

+ Response 200

### Uncomplete order [DELETE]

+ Response 200


## SubOrder [/order/{id}/suborder]

### Get the list of suborders [GET]

+ Response 200

        [{
          "id": 3,  
          "name" : "SuperClient - Project Y phase2 system administration",
          "links" : [{
            "href" : "/order/3",
            "rel"  : "self"
          }]
        }, 
         {
          "id": 4,  
          "name" : "SuperClient - Project X phase1 templating",
          "links" : [{
            "href" : "/order/4",
            "rel"  : "self"
          }]
        }]        
       
       
### Create SubOrder aka Split order [POST]

+ Request (application/json)

        {
            "allocated_budget" : 100,
            "name" : "SubOrder on SuperClient phase2",
            "team" : {
                "id" : 4
            }
        }

+ Response 201
    
        { 
            "id" : 2,
            "links" : [{
                "href" : "/order/2",
                "rel"  : "self"
            }]
        }

# Group Task API

## Tasks Collection [/tasks/?paid={paid_status}&sorted_by={sorted_by}&search_query={query}]
### List all Tasks [GET]

+ Parameters

    + paid (boolean) - Filtering on paid tasks

    + sorted_by (string) - Sorting on tasks
    
        + Values
        
            + `external_id`
            + `budget`

    + search_query (string) - Search on tasks using external_id as a key


+ Response 200 (application/json)

        [{
          "id": 1,  
          "external_id" : "OPS-122",
          "links" : [{
            "href" : "/task/1",
            "rel"  : "self"
          },
          {
            "href" : "http://jira.opsway.com/browse/OPS-122",
            "rel"  : "external"
          }]
        }, 
         {
          "id": 2,  
          "external_id" : "OPS-123",
          "links" : [{
            "href" : "/task/2",
            "rel"  : "self"
          },
          {
            "href" : "http://jira.opsway.com/browse/OPS-123",
            "rel"  : "external"
          }]
        }]

### Create a Task [POST]
+ Request (application/json)

        {
          "external_id" : "OPS-126"
        }

+ Response 201 (application/json)

        { 
            "id" : 5,
            "links" : [{
                "href" : "/task/5",
                "rel"  : "self"
            },
            {
                "href" : "http://jira.opsway.com/browse/OPS-126",
                "rel"  : "external"
            }]
        }


## Task [/task/{id}]
A single Task object with all its details

+ Parameters
    + id (required, number, `2`) ... Numeric `id` of the Order to perform action with. 

### Retrieve a Task [GET]

+ Response 200 (application/json)

        {
          "id": 5, 
          "external_id": "OPS-126", 
          "budget": 100.00, 
          "paid" : false,
          "accepted" : true,
          "resolver" : {
            "name" : "Alexander Gornov",
            "href" : "/user/10",
            "id" : 10
          },
          "links" : [{
            "href" : "/task/5",
            "rel"  : "self"
          },
          {
            "href" : "/task/5/accept",
            "rel"  : "accept"
          },
          {
            "href" : "/task/5/resolver",
            "rel"  : "resolver"
          },
          {
            "href" : "/task/5/budget",
            "rel"  : "budget"
          }
          ],
          "orders": [
            {
              "id": 5,
              "name": "Test",
              "invoiced_budget": "1500.0",
              "allocatable_budget": "1000.0",
              "free_budget": "900.0",
              "links": {
                "url": "/orders/5",
                "rel": "self"
              }
            },
            {
              "id": 8,
              "name": "Test2",
              "invoiced_budget": "2000.0",
              "allocatable_budget": "500.0",
              "free_budget": "350.0",
              "links": {
                "url": "/orders/8",
                "rel": "self"
              }
            }
          ]
        }


## Accept an Task [/task/{id}/accept] 

### Set accepted status in Task [POST]

+ Response 200

### Remove accepted status from Task [DELETE]

+ Response 200


## Task Resolver [/task/{id}/resolver] 

### Set resolver in Task [POST]

+ Request (application/json)

        {
            "id" : 9
        }

+ Response 200

### Remove resolver from Task [DELETE]

+ Response 200

## Task Budget [/task/{id}/budget] 

### Set budget in Task [POST]
Updates task budgets, putting its individual budgets from order as supplied. Budget information is complete overwritten when action is called

+ Request (application/json)

        {[
            { 
              "order_id" : 2,
              "budget"   : 10
            },
            { 
              "order_id" : 3,
              "budget"   : 5
            },
            { 
              "order_id" : 5,
              "budget"   : 11
            }
        ]}

+ Response 200

### Get budgets for Task [GET]

+ Request (application/json)

        {'budget' : [
            { 
              "order_id" : 2,
              "budget"   : 10
            },
            { 
              "order_id" : 3,
              "budget"   : 5
            },
            { 
              "order_id" : 5,
              "budget"   : 11
            }
        ]}

+ Response 200


# Group Invoice API

## Invoice Collection [/invoices/?paid={paid_status}&sorted_by={sorted_by}&search_query={query}]
### List all Invoices [GET]


+ Parameters

    + paid (boolean) - Filtering on paid invoices

    + sorted_by (string) - Sorting on invoices
    
        + Values
        
            + `comment`
            + `client`

    + search_query (string) - Search on invoices using external_id OR client as a key


+ Response 200 (application/json)

        [{
          "id": 1,  
          "links" : [{
            "href" : "/invoice/1",
            "rel"  : "self"
          }]
        }, 
         {
          "id": 2,  
          "links" : [{
            "href" : "/invoice/2",
            "rel"  : "self"
          }]
        }]

### Create an Invoice [POST]
+ Request (application/json)

        {
          "external_id" : "67899000000303001"
        }

+ Response 201 (application/json)

        { 
            "id" : 5,
            "links" : [{
                "href" : "/invoice/5",
                "rel"  : "self"
          }]
        }

## Invoice [/invoice/{id}]
A single Invoice object with all its details

+ Parameters
    + id (required, number, `2`) ... Numeric `id` of the Order to perform action with. 

### Retrieve an Invoice [GET]

+ Response 200 (application/json)

        {
          "id": 5, 
          "external_id" : "67899000000303001",
          "paid" : false,
          "links" : [{
            "href" : "/invoice/5",
            "rel"  : "self"
          }],
          "orders": [
            {
              "id": 15,
              "name": "Test2",
              "invoiced_budget": "50.0",
              "allocatable_budget": "30.0",
              "free_budget": "10.0",
              "links": {
                "url": "/orders/15",
                "rel": "self"
                }
              }
          ]
        }

### Remove an Invoice [DELETE]
+ Response 200

## Set paid status [/invoice/{id}/paid] 

### Mark Invoice as paid [POST]

+ Response 200

### Remove paid status from Invoice [DELETE]

+ Response 200

# Group Transaction API

## Transaction Collection [/transactions?user={user_id}&team={team_id}&sorted_by={sorted_by}&search_query={query}]
### List all Transactions [GET]

+ Parameters

    + user (int) - Filtering by user id
    + team (int) - Filtering by team id

    + sorted_by (string) - Sorting on tasks
    
        + Values
        
            + `total`
            + `created_at`

    + search_query (string) - Search on tasks using comment as a key


+ Response 200 (application/json)

        [{
          "id": 1, ,
          "comment": "122 Balance payment",
          "type": "payment",
          "total": "20.0",
          "owner": {
                "id": 3,
                "type": "user"
                "href" : "/user/3"
          },
          "links" : [{
            "href" : "/transaction/1",
            "rel"  : "self"
          }]
        }, 
         {
          "id": 2,
          "comment": "123",
          "type": "balance",
          "total": "10.0",
          "owner": {
                "id": 3,
                "type": "user"
                "href" : "/user/3"
          },
          "links" : [{
            "href" : "/transaction/2",
            "rel"  : "self"
          }]
        }]

## Transaction [/transaction/{id}]
A single Transaction object with all its details

+ Parameters
    + id (required, number, `2`) ... Numeric `id` of the Transaction to perform action with. 

### Retrieve a Transaction [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "timestamp": 1421333947,
            "owner": {
                "id": 3,
                "type": "user"
                "href" : "/user/3"
            },
            "total": "10.0",
            "comment": "123"
        }


# Group User API

## User Collection [/users]
### List all Users [GET]
+ Response 200 (application/json)

        [{
            "id": 1,
            "name": "Test",
            "login": "usr",
            "team": {
                "name": "Test Team",
                "href": "/team/1"
            },
            "role": "Manager",
            "links": {
                "href": "/user/1",
                "rel": "self"
            }
        },
        {
            "id": 2,
            "name": "Test",
            "login": "usr",
            "team": {
                "name": "Test Team",
                "href": "/team/1"
            },
            "role": "Manager",
            "links": {
                "href": "/user/1",
                "rel": "self"
            }
        }]

## User [/user/{id}]
A single User object with all its details

+ Parameters
    + id (required, number, `2`) ... Numeric `id` of the Transaction to perform action with. 

### Retrieve an User [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Test",
            "login": "usr",
            "team": {
                "name": "Test Team",
                "href": "/team/1"
            },
            "daily_rate": 54.30,
            "role": "Manager",
            "links": {
                "href": "/user/1",
                "rel": "self"
            },
            "balance_account_state": 31.22,
            "income__account_state": -123.12
        }
        

# Group Team API

## Team Collection [/teams]
### List all Teams [GET]
+ Response 200 (application/json)

        [{
            "id": 1,
            "name": "Test Team",
            "links": {
                "id": 1,
                "href": "/team/1",
                "rel": "self"
            }
        },    
        {
            "id": 1,
            "name": "Test Team",
            "links": {
                "id": 1,
                "href": "/team/1",
                "rel": "self"
            }
        }]

## Team [/team/{id}]
A single Team object with all its details

+ Parameters
    + id (required, number, `2`) ... Numeric `id` of the Transaction to perform action with. 

### Retrieve an Team [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Test Team",
            "balance_account_state": 120.0,
            "income_account_state": -10.31
        }

    
# Group Status API

## Status [/status]

### Return all status resources

+ Response 200 (application/json)

        [{
            "name": "Selfcheck",
            "links": {
                "href": "/status/selfcheck"
            }
        }]


## Self-check [/status/selfcheck]
### Run a self-check [GET]

Returns a list of errors found or empty response in case everything is correct

+ Response 200 (application/json)

        {"errors" :
         ["Incorrect number of transactions for issue 22875",
          "Order 623 is expected to be paid"
         ]   
        }



# Group ERRORS

API returns the following HTTP error codes

 - HTTP 401 Unauthorized request
 - HTTP 403 Forbidden
 - HTTP 405 Method not allowed
 - HTTP 422 Failed request

 
In case of error, API returns error list with descriptions, in the following format

{
    "errors" : [
        "Order team is different from resolver team",
        "Allocated budget should be positive"
    ]
}
 



# Group SORTING AND FILTERING

Sorting and filtering is handled with URL query parameters which applies only for GET requests

Filtering

  - ?param=value

Value can be in

  - boolean (true/false/1/0)
  - number (integer)


Sorting is done using special parameter:

  - ?sorted_by=value 

Where value is parameter name that can be used for filtering on object and prepending suffixes _desc or _asc to parameter name.
Where _desc/_asc stand for sorting direction, descending or ascending respectively. Default sorting direction is ascending.

Examples:

  - /orders?sorted_by=total
  - /orders?sorted_by=free_budget_asc
  - /tasks?sorted_by=paid_desc

You can use multiple parameters to sort, which are applied in sequance

  - /tasks/?sorted_by=external_id_desc,budget_asc

Pagination

Adding parameters limit and page, one can get a subset of results. page is counted up from 1, and object for limit parameter are counted from 1 and up.

Examples:

  - /tasks?paid=true&limit=10&page=4   In this case results 41-50 will be on current page


Searching is available through parameter ?search_query=value, where value is search in a list of parameters with OR logic. List of parameters is specific for each object type (see in respective resource definitions)